### ISSUE TITLE
Update deprecated eslint-config-humanmade package

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-build-tools#275]
When running ` npm install --no-save pressbooks-build-tools` we receive a `npm WARN deprecated eslint-config-humanmade@0.7.0: Package moved to @humanmade/eslint-config` warning. We should update the package reference: https://github.com/pressbooks/pressbooks-build-tools/blob/37a9f334f2cc545d6925c75f2bbc54cbd1d5cacb/package.json#L35

Old (deprecated) package: https://www.npmjs.com/package/eslint-config-humanmade
New package: https://www.npmjs.com/package/@humanmade/eslint-config

**Comment by richard015ar** [comment]
It was closed because the PR. We would like to test before close it.

**Comment by greatislander** [comment]
@SteelWagstaff This is done and should be closed.
